Feature 105 side wide search
Metatavu/pedanet-react-theme pull request #107
Opened 2022-05-05 14:31 UTC by platonovsimeon

Resolves #105

2022-05-07 08:36 UTC, anttileppa requested changes

2022-05-07 08:36 UTC, anttileppa commented on src/components/BasicLayout.tsx
> +  private renderSearchbar = () => {
Add tsdocs

2022-05-07 08:36 UTC, anttileppa commented on src/components/pages/SearchResultsPage.tsx
> +interface Props {
Add tsdocs

2022-05-07 08:36 UTC, anttileppa commented on src/components/pages/SearchResultsPage.tsx
> +interface State {
Add tsdocs

2022-05-07 08:36 UTC, anttileppa commented on src/components/pages/SearchResultsPage.tsx
> +interface SearchResult {
Add tsdocs

2022-05-07 08:36 UTC, anttileppa commented on webpack.config.js
> -  mode: "production",
revert this change

2022-05-09 05:54 UTC, platonovsimeon commented on package.json
> -    "material-ui": "^0.20.2",
Yes

2022-05-09 05:58 UTC, platonovsimeon commented on src/components/BasicLayout.tsx
> +interface SearchOption {
Fixed

2022-05-09 05:58 UTC, platonovsimeon commented on src/components/BasicLayout.tsx
> +  private onSearchChange = async (_: React.ChangeEvent<{}>, value: string) => {
Fixed

2022-05-09 05:58 UTC, platonovsimeon commented on src/components/BasicLayout.tsx
> +  private renderSearchbar = () => {
Fixed

2022-05-09 05:58 UTC, platonovsimeon commented on src/components/pages/SearchResultsPage.tsx
> +interface Props {
Fixed

2022-05-09 05:58 UTC, platonovsimeon commented on src/components/pages/SearchResultsPage.tsx
> +interface State {
Fixed

2022-05-09 05:58 UTC, platonovsimeon commented on src/components/pages/SearchResultsPage.tsx
> +interface SearchResult {
Fixed

2022-05-09 05:58 UTC, platonovsimeon commented on webpack.config.js
> -  mode: "production",
Fixed

2022-05-09 13:55 UTC, anttileppa approved these changes

2022-05-09 13:55 UTC, anttileppa commented on src/components/BasicLayout.tsx
> +  private renderGroup = (params: any) => {
Add tsdocs

2022-05-09 13:55 UTC, anttileppa commented on src/components/BasicLayout.tsx
> +  private renderOption = (option: SearchOption) => {
Add tsdocs

2022-05-10 05:44 UTC, merged